# Generated by Django 5.0.6 on 2024-05-13 20:11

import isbn_field.fields
import isbn_field.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=isbn_field.fields.ISBNField(default=1, max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN'),
            preserve_default=False,
        ),
    ]
