# Generated by Django 5.0.6 on 2024-05-13 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
