# Generated by Django 5.0.6 on 2024-05-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_gender', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
