# Generated by Django 5.0.6 on 2024-05-13 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_genderbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='gender_name',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='books.genderbooks', verbose_name='Gender Name'),
            preserve_default=False,
        ),
    ]
